function vs_About

win_width = 360;
win_height = 420;

versn = 'v1.33';
vdate = 'March 7, 2018';

acknowledgements = {'Acknowledgements: ', ...
                    [], ...
                    'Code contributors:', ...
                    '  - Markus Iseli (harmonic correction formula, bandwidth mapping function, peak-picking function)', ...
                    '  - Henry Tehrani (EMU file format)', ...
                    '  - Kristine Yu (Praat integration, SHR measures, MacOS compatibility)', ...
                    '  - Soo Jin Park (estimated bandwidth usage, SoE measure)', ...
                    [], ...
                    'STRAIGHT algorithm:', ...
	                '  - Hideki Karahara (http://www.wakayama-u.ac.jp/~kawahara/)', ...
                    [], ...
                    'Snack sound toolkit:', ...
                	'  - KTH (http://www.speech.kth.se/snack/)', ...
                    [], ...
                    'Praat:', ...
                    '  - http://www.fon.hum.uva.nl/praat/download_win.html', ...
                    [], ...
                    'fminsearchbnd.m:', ...
                    '  - John D''Errico (http://www.mathworks.com/matlabcentral/fileexchange/8277)', ...
                    [], ...
                    'Documentation:', ...
                    '  - Chad Vicenik', ...
                    [], ...
                    'Early testers:', ...
                    '  - Christina Esposito', ...
                    '  - Marc Garellek', ...
                    '  - Patricia Keating', ...
                    '  - Sameer Khan', ...
                    '  - Jianjing Kuang', ...
                    '  - Chad Vicenik', ...
                    '  - Kristine Yu', ...
                    [], ...
                    'Special thanks to:', ...
                    '  - Patricia Keating', ...
                    '  - Abeer Alwan', ...
                    '  - Jody Kreiman'};


scrsz = get(0, 'ScreenSize');

fig = figure('Visible', 'on', 'Position' , [round(scrsz(3)/2 - win_width/2) round(scrsz(4)/2 - win_height/2) win_width win_height],...
      'WindowStyle', 'modal', 'NumberTitle', 'off', 'Name', 'About...', ...
      'Color', [0.941 0.941 0.941]);

pushbutton_OK = uicontrol('Style', 'pushbutton', 'String', 'OK', ...
                'Position', [130, 5, 100, 40], ...
                'FontSize', 10, ...
                'FontWeight', 'bold', ...
                'Callback', {@pushbutton_OK_Callback});
            
text_title = uicontrol('Style', 'text', 'String', ['VoiceSauce ' versn], ...
             'Position', [1, 380, win_width, 20], ...
             'FontSize', 12, 'FontWeight', 'bold', ...
             'HorizontalAlignment', 'center', ...
             'BackgroundColor', [0.941 0.941 0.941]);
            
text_author = uicontrol('Style', 'text', 'String', {'Yen-Liang Shue (yshue@ucla.edu)', [], 'http://www.phonetics.ucla.edu/voicesauce/', vdate}, ...
              'Position', [1, 300, win_width, 60], ...
              'FontSize', 8, 'HorizontalAlignment', 'center', ...
              'BackgroundColor', [0.941 0.941 0.941], ...
              'Enable', 'on');
         
listbox_ack = uicontrol('Style', 'listbox', 'String', acknowledgements, ...
              'Position', [20, 50, win_width - 2*20, 240]);
          
          
% callback function for pushbutton_OK            
function pushbutton_OK_Callback(source,eventdata)
delete(gcf);

